accounts/urls.py
from django.conf.urls import patterns, include, url

from accounts import views

urlpatterns = patterns('',  # url(r'^', views.login_in, name='login'),
                       url(r'^', views.login, name='login'),
                       url(r'^login/', views.login, name='login'),
                       url(r'^logout/', views.logout, name='logout'),
                       url(r'^register/', views.register, name='register'),
                       )

video_cloud/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from video_cloud import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^cameras/$', views.cameras, name='cameras'),
                       url(r'^pricing/$', views.pricing, name='pricing'),
                       url(r'^contact/$', views.contact, name='contact'),
                       url(r'^helps/$', views.helps, name='helps'),
                       url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                       )

accounts/views.py
# -*- coding: utf-8 -*-e 
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.core.context_processors import csrf
from django.shortcuts import render_to_response, redirect


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        args['username'] = auth.get_user(request).username
        if user is not None and user.is_active:
            # Правильный пароль и пользователь "активен"
            auth.login(request, user)
            # Перенаправление на "правильную" страницу
            return redirect("/")
        else:
            # todo сделать ошибку ввода пароля
            args['login_error'] = "Не правильный логин или пароль!"
            # Отображение страницы с ошибкой
            return render_to_response("login.html", args)
    else:
        return render_to_response("login.html", args)


def logout(request):
    auth.logout(request)
    # Перенаправление на страницу.
    return redirect("/accounts/login/")


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'],
                                        password=newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect("/testing/")
        else:
            args['form'] = newuser_form
    return render_to_response('register.html', args)

video_cloud/views.py
# -*- coding: utf-8 -*-
import random
from django.contrib import auth
from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template import Context, loader


def index(request):
    args = {'username': auth.get_user(request).username}
    print (request)
    return render_to_response('index.html', args)

def cameras(request):
    args = {'username': auth.get_user(request).username}
    return render_to_response('cameras.html', args)

def pricing(request):
    args = {'username': auth.get_user(request).username}
    return render_to_response('pricing.html', args)

def contact(request):
    args = {'username': auth.get_user(request).username}
    return render_to_response('contact.html', args)

def helps(request):
    args = {'username': auth.get_user(request).username}
    return render_to_response('helps.html', args)

accounts/templates/login.html
{% extends "base.html" %}
{% block content %}
    <section id="three" class="section swatch-white" style="margin-bottom:18%" >
	
        <div class="container-fullwidth" style="height: 100px;">

            <form class="form-horizontal" action="" method="POST">
            {% csrf_token %}
            <div class="form-group" >
                <label for="username" class="control-label col-sm-2">Логин</label>

                <div class="col-sm-10">
                    <input type="text" class="form-control" name="username" placeholder="Логин">
                </div>
            </div>
            <div class="form-group" >
                <label class="col-sm-2 control-label">Пароль</label>

                <div class="col-sm-10">
                    <input type="password" name="password" class="form-control" placeholder="Пароль">
                </div>
                {% if login_error %}
                    <div class="col-sm-offset-2 col-sm-10" >
                        <label class="error">{{ login_error }}</label>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-offset-2 col-sm-10">
                <div class="form-group">
                    {{ form.recaptcha }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Войти</button>
                    <a href="{% url 'accounts:register' %}" class="btn btn-info" role="button"
                       style="visibility: hidden;">Регистрация</a>
                </div>
            </div>
        </form>
        </div>
    </section>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block content %}
    {% block login %}
        <div class="large-ofsset-3 large-6 columns">
            <form action="" method="post">
                {% csrf_token %}
                {{ form }}
                <input class="button" type="submit" value="Зарегистрироваться">
            </form>
        </div>

    {% endblock %}
{% endblock %}

video_cloud/templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,300italic,400italic,600italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/color-defaults.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-white.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-blue.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-gray.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-black.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-white-black.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-white-green.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/swatch-white-red.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/revolution.min.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" media="screen">

    <script type="text/javascript" src="{% static 'assets/js/jquery.js'%}"></script>
</head>
<body class="normal-header">
<div id="masthead" class="navbar navbar-static-top swatch-white navbar-sticky" role="banner">
    {% include 'nav-bar.html'%}
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<footer id="footer" role="contentinfo">
    {% include 'footer.html'%}
</footer>
 {% load staticfiles %}
<script type="text/javascript" src="{% static 'assets/js/packages.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/theme.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/revolution.js' %}"></script>


</body>
</html>

video_cloud/templates/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Контакты
{% endblock %}
{% block content %}

    <article>
        <section class="section swatch-black  section-text-shadow section-inner-shadow">
            <div class="background-media"
                 style="background-image: url('{% static 'assets/images/contacts/background.jpg' %}'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed; background-position: 50% 44%;"
                 data-start="background-position:"
                 data-70-top-bottom="background-position:">
            </div>
            <div class="background-overlay grid-overlay-30 " style="background-color: rgba(0,0,0,0.3);"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <header class="text-center  element-medium-top element-medium-bottom not-condensed os-animation"
                                data-os-animation="fadeIn" data-os-animation-delay=".4s" data-70-top-bottom="opacity:0"
                                data-start="opacity:1" data-center="opacity:1">
                            <h1 class="super hairline bordered-normal">
                                Контакты
                            </h1>
                        </header>
                    </div>
                </div>
            </div>
        </section>
        <section id="two" class="section swatch-white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <header class="text-center element-normal-top element-medium-bottom condensed os-animation"
                                data-os-animation="fadeInUp" data-os-animation-delay="0s">
                            <h2 class="figure-caption-title bordered bordered bordered-link">
                                <P style="color:#82C9ED"> Обратная связь</P>
                            </h2>

                        </header>
                    </div>
                </div>
                <div class="container content">
                    <div class="row margin-bottom-30">
                        <!-- Contacts -->
                        <div class="col-md-16">
                            <!-- Business Hours -->

                            <div class="col-md-8 text-left small-screen-center os-animation element-normal-bottom"
                                 data-os-animation="fadeInRight" data-os-animation-delay="0.3s">
                                <form id="contactForm" class="contact-form">
                                    <div class="form-group form-icon-group">
                                        <input class="form-control" id="name" name="name" placeholder="Ваше имя *"
                                               type="text" required/>
                                        <i class="fa fa-user"></i>
                                    </div>
                                    <div class="form-group form-icon-group">
                                        <input class="form-control" id="email" name="email" placeholder="Ваш Е-майл *"
                                               type="email" required>
                                        <i class="fa fa-envelope"></i>
                                    </div>
                                    <div class="form-group form-icon-group">
                                        <textarea class="form-control" id="message" name="message"
                                                  placeholder="Сообщение" rows="10" required></textarea>
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                    <div>
                                        <input type="submit" value="Отправить" class="btn btn-primary">
                                    </div>
                                    <div id="messages"></div>
                                </form>
                            </div>
                            <div class="col-md-3 col-md-offset-1">
                                <div class="figure-caption-title bordered bordered bordered-link">
                                    <h2 style="color:#82C9ED">Контакты</h2>
                                </div>
                                <ul class="list-unstyled who margin-bottom-30">
                                    <li><p href="#"><i class="fa fa-phone"></i> 55-59-54</p></li>
                                    <li><p href="#"><i class="fa fa-globe"></i> http://video_cloud.com</p></li>
                                </ul>

                                <!-- Business Hours -->
                                <div class="figure-caption-title bordered bordered bordered-link">
                                    <h2 style="color:#82C9ED">Реквизиты</h2>
                                </div>
                                <ul class="list-unstyled margin-bottom-30">
                                    <li>ООО «Video cloud»</li>
                                    <li>ИНН - 6568986856</li>
                                    <li>ОГРН - 67867575875</li>
                                    <li>Юр. адрес - 429566 г. Чебоксары ул. Николаева . д.72</li>
                                    <li>Факт. адрес - 429566 г. Чебоксары ул. Николаева. д.72</li>
                                </ul>
                            </div>
                            <!--/col-md-3--><!--/row-->
                        </div>
                    </div>
        </section>
        <section class="section swatch-black  section-text-shadow section-inner-shadow">
            <div class="background-media"
                 style="background-image: url('{% static 'assets/images/contacts/background.jpg' %}'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed; background-position: 50% 44%;"
                 data-start="background-position:"
                 data-70-top-bottom="background-position:">
            </div>
            <div class="background-overlay grid-overlay-30 " style="background-color: rgba(0,0,0,0.3);"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <header class="text-center element-normal-top element-short-bottom condensed os-animation"
                                data-os-animation="fadeIn" data-os-animation-delay=".4s" data-70-top-bottom="opacity:0"
                                data-start="opacity:1" data-center="opacity:1">

                        </header>
                    </div>
                </div>
            </div>
        </section>
    </article>

{% endblock %}

video_cloud/templates/footer.html
<section class="section swatch-black">
    <div class="container">
        <div class="row element-normal-top element-normal-bottom">
            <div class="col-md-3">
                <div id="recent-posts-4" class="sidebar-widget  widget_recent_entries">
                    {% block recent-posts %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-md-3">
                <div id="categories-4" class="sidebar-widget  widget_categories">
                    {% block categories %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-md-3">
                <div id="archives-4" class="sidebar-widget  widget_archive">
                    {% block archives %}{% endblock %}
                </div>
            </div>
            <div class="col-md-3">
                <div id="tag_cloud-3" class="sidebar-widget  widget_tag_cloud">
                    {% block tags %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</section>

video_cloud/templates/helps.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    Помощь
{% endblock %}
{% block content %}
    <article>
        <section class="section swatch-black  section-text-shadow section-inner-shadow">
            <div class="background-media"
                 style="background-image: url('{% static 'assets/images/helps/background.jpg' %}'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed; background-position: 50% 44%;"
                 data-start="background-position:"
                 data-70-top-bottom="background-position:">
            </div>
            <div class="background-overlay grid-overlay-30 " style="background-color: rgba(0,0,0,0.3);"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <header class="text-center  element-medium-top element-medium-bottom not-condensed os-animation"
                                data-os-animation="fadeIn" data-os-animation-delay=".4s" data-70-top-bottom="opacity:0"
                                data-start="opacity:1" data-center="opacity:1">
                            <h1 class="super hairline bordered-normal">
                                Помощь
                            </h1>
                        </header>
                    </div>
                </div>
            </div>
        </section>
        <section class="section swatch-white ">

            <div class="container">
                <div class="row">
                    <div class="col-md-16 text-left">


                        <header class="text-center element-normal-top  ">
                            <h2 class="figure-caption-title bordered bordered bordered-link">
                                <p style="color:#82C9ED"> Часто задаваемы вопросы </p>
                            </h2>
                        </header>

                        <div class="row">
                            <div class="col-md-3"></div>
                            <div class="col-md-10">
                                <div id="accordion_836"
                                     class="panel-group  element-short-top element-short-bottom os-animation"
                                     data-os-animation="fadeInLeft" data-os-animation-delay="0s">
                                    <div>

                                        <div class="panel-heading">
                                            <a href="#group_1" data-toggle="collapse"> Как начать пользоваться
                                                сервисом?</a>
                                        </div>
                                        <div id="group_1" class="panel-collapse collapse ">
                                            <div class="panel-body">
                                                <div class=" element-no-top element-no-bottom" data-os-animation="none"
                                                     data-os-animation-delay="0s">
                                                    <p>


                                                        1. Настройка сервиса Video cloud на моделях RVi-IPC11,
                                                        RVi-IPC12,
                                                        RVi-IPC33M, RVi-IPC33V, RVi-IPC41, RVi-IPC41DNL, RVi-IPC42,
                                                        RVi-IPC43, RVi-IPC43M3, RVi-IPC43DNS, RVi-IPC22DN NEW.<br>
                                                        2. Настройка сервиса Video cloud на моделях RVi-IPC11S,
                                                        RVi-IPC12SW, RVi-IPC31S, RVi-IPC32S, RVi-IPC41LS, RVi-IPC42LS,
                                                        RVi-IPC31MS-IR, RVi-IPC32MS-IR.

                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div>
                                        <div class="panel-heading">
                                            <a href="#group_2" data-toggle="collapse">Какие камеры поддерживаются
                                                сервисом?</a>
                                        </div>
                                        <div id="group_2" class="panel-collapse collapse ">
                                            <div class="panel-body">
                                                <div class=" element-no-top element-no-bottom" data-os-animation="none"
                                                     data-os-animation-delay="0s">
                                                    <p> Полный список камер поддерживаемых сервисом вы можете найти на
                                                        странице <a href="/#">камеры</a></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="panel-heading">
                                            <a href="#group_3" data-toggle="collapse">Требуется ли статический IP-адрес
                                                для пользования сервисом Video cloud?</a>
                                        </div>
                                        <div id="group_3" class="panel-collapse collapse ">
                                            <div class="panel-body">
                                                <div class=" element-no-top element-no-bottom" data-os-animation="none"
                                                     data-os-animation-delay="0s">
                                                    <p>Для использования сервиса облачного видеонаблюдения Video cloud
                                                        статический IP-адрес не требуется.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>


                    </div>
                </div>
            </div>
        </section>
        <section class="section swatch-black  section-text-shadow section-inner-shadow">
            <div class="background-media"
                 style="background-image: url('{% static 'assets/images/helps/background.jpg' %}'); background-repeat: no-repeat; background-size: cover; background-attachment: fixed; background-position: 50% 44%;"
                 data-start="background-position:"
                 data-70-top-bottom="background-position:">
            </div>
            <div class="background-overlay grid-overlay-30 " style="background-color: rgba(0,0,0,0.3);"></div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <header class="text-center element-normal-top element-short-bottom condensed os-animation"
                                data-os-animation="fadeIn" data-os-animation-delay=".4s" data-70-top-bottom="opacity:0"
                                data-start="opacity:1" data-center="opacity:1">

                        </header>
                    </div>
                </div>
            </div>
        </section>
    </article>

{% endblock %}

video_cloud/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<article>
    <section id="three" class="section swatch-black">
        <div class="container-fullwidth">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="tp-banner-container">
                        <div class="tp-banner">
                            {% include "index/index-banner.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="two" class="section swatch-white">
        <div class="container">
            <div id="services" class="row">
                {% include "index/index-services.html" %}
            </div>
        </div>
    </section>
    <section id="help-watch" class="section swatch-black section-text-shadow section-inner-shadow">
        <div class="background-overlay grid-overlay-0 " style="background-color: rgba(46,51,57,1);"></div>
        <div class="container">
            {% include "index/index-help-watch.html" %}
        </div>
    </section>
    <section id="about_service" class="section swatch-white">
        <div class="container">
            {% include "index/index-about_service.html" %}
        </div>
    </section>
    <section id="lets_register" class="section swatch-black section-text-shadow section-inner-shadow">
        <div class="background-overlay grid-overlay-0 " style="background-color: rgba(46,51,57,1);"></div>
        <div class="container">
            {% include "index/index-lets_register.html" %}
        </div>
    </section>
</article>
<script type="text/javascript">
    jQuery(document).ready(function()
    {
        jQuery('.tp-banner').show().revolution(
                {
                    delay: 8000,
                    startwidth: 1170,
                    startheight: 480,
                    onHoverStop: "on", // Stop Banner Timer at Hover on Slide on/off
                    thumbWidth: 100, // Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
                    thumbHeight: 50,
                    thumbAmount: 3,
                    hideThumbs: 0,
                    navigationType: "bullet", // bullet, thumb, none
                    navigationArrows: "solo", // nexttobullets, solo (old name verticalcentered), none
                    navigationStyle: "round", // round,square,navbar,round-old,square-old,navbar-old, or any from the list in the docu (choose between 50+ different item), custom
                    navigationHAlign: "center", // Vertical Align top,center,bottom
                    navigationVAlign: "bottom", // Horizontal Align left,center,right
                    navigationHOffset: 0,
                    navigationVOffset: 20,
                    soloArrowLeftHalign: "left",
                    soloArrowLeftValign: "center",
                    soloArrowLeftHOffset: 20,
                    soloArrowLeftVOffset: 0,
                    soloArrowRightHalign: "right",
                    soloArrowRightValign: "center",
                    soloArrowRightHOffset: 20,
                    soloArrowRightVOffset: 0,
                    touchenabled: "on", // Enable Swipe Function : on/off
                    stopAtSlide: -1, // Стоп таймер, если Слайд "х" была достигнута. Если stopAfterLoops установлен в 0, то он останавливается уже в первом контуре в слайд-X, который определен. -1 Означает, что не остановится на любом слайде. stopAfterLoops не имеет Sinn в этом случае.
                    stopAfterLoops: -1, // Стоп таймер, если все слайды сыграли "х" раз. Он будет останавливаться на слайде, который определяется с помощью stopAtSlide: х, если установлен в -1 слайд никогда не остановить автоматический
                    hideCaptionAtLimit: 0, // Он определяет, если подпись должна быть показана под разрешение экрана
                    hideAllCaptionAtLilmit: 0, // Скрыть все подписи ширины браузера, составляет менее этой величины
                    hideSliderAtLimit: 0, // Скрыть все ползунок, и остановить также функции, если ширина браузера меньше этого значения
                    fullWidth: "on",
                    shadow: 0
                });
    });
</script>
{% endblock %}

video_cloud/templates/index/index-lets_register.html
{% load staticfiles %}
<div class="row">
    <div class="col-md-12 text-center">
        <header class="text-center element-tall-top element-medium-bottom os-animation condensed"
                data-os-animation="fadeIn" data-os-animation-delay="0s">
            <h1 class="bigger hairline bordered-normal">
                <b> video cloud </b> — это облачный сервис видеонаблюдения через Интернет.
            </h1>
        </header>
        <a href="contact-big-map.html"
           class="btn btn-primary btn-lg element-short-top element-normal-bottom os-animation" target="_self"
           data-os-animation="fadeInUp" data-os-animation-delay="0s">
            Зарегистрироваться
        </a>
    </div>
</div>

video_cloud/templates/nav-bar.html
{% load staticfiles %}

<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".main-navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="{% url 'index' %}" class="navbar-brand">
            <img src="{% static 'assets/images/omega.png' %}" alt="Иконка компании">video cloud
        </a>
    </div>

    <nav class="collapse navbar-collapse main-navbar" role="navigation">

        <ul class="nav navbar-nav">
            <li class="dropdown menu-item-object-oxy_mega_menu ">
                <a href="{% url 'index' %}" class="dropdown-toggle">Главная</a>
            </li>
            <li class="dropdown">
                <a href="{% url 'cameras' %}" class="dropdown-toggle">Камеры</a>
            </li>
            <li class="dropdown">
                <a href="{% url 'pricing' %}" class="dropdown-toggle">Тарифы</a>
            </li>

            <li class="dropdown">
                <a href="{% url 'helps' %}" class="dropdown-toggle">Помощь</a>
            </li>
            <li class="dropdown">
                <a href="{% url 'contact' %}"  class="dropdown-toggle">Контакты</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if username %}
            <li><a href="{% url 'accounts:logout'%}"> Выйти ({{ username }})</a></li>
            {% else %}
            <li><a href="">Зарегистрироваться</a></li>
            <li><a href="{% url 'accounts:login'%}"> Войти</a></li>
            {% endif %}
        </ul>
    </nav>
</div>